version: '2'
services:
  mysql:
    build: ./mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: pass
      TZ: Asia/Tokyo
    volumes:
      - ./mysqldata:/var/lib/mysql
  app:
    build: ./app
    links:
      - mysql


